---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname actions-runner-controller
  namespace: flux-system
spec:
  targetNamespace: system-controllers
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/main/apps/system-controllers/actions-runner-controller/operator/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: true
  dependsOn:
    - name: external-secrets-stores

# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname actions-runner-controller-runners
#   namespace: flux-system
# spec:
#   targetNamespace: system-controllers
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname
#   interval: 10m
#   path: "./kubernetes/main/apps/system-controllers/actions-runner-controller/runners/app"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: bmrf-ops
#   wait: false
#   dependsOn:
#     - name: actions-runner-controller