---
ingress:
  - hostname: ${SECRET_DOMAIN}"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.${SECRET_DOMAIN}
  - hostname: "*.${SECRET_DOMAIN}"
    service: https://nginx-external-controller.network.svc.cluster.local:443
    originRequest:
      originServerName: ingress-ext.${SECRET_DOMAIN}
  - service: http_status:404
