---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: minio-operator
resources:
  - ./namespace.yaml
  - ./helmrelease.yaml
# configMapGenerator:
#   - name: minio-operator-values
#     files:
#       - values.yaml=values.yaml
# configurations:
#   - kustomizeconfig.yaml