---
nodeFeatureRule:
  createCRD: true
worker:
  annotations:
    configmap.reloader.stakater.com/reload: auto
  resources:
    requests:
      cpu: 5m
      memory: 48Mi
    limits:
      memory: 48Mi
  config:
    core:
      sources:
        - custom
        - pci
        - usb
    sources:
      usb:
        deviceClassWhitelist:
          - "02"
          - "03"
          - "0e"
          - "ef"
          - "fe"
          - "ff"
        deviceLabelFields:
          - class
          - vendor
          - device
