---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-github-flow
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-github-flow
    creationPolicy: Owner
  data:
    - secretKey: client-id
      remoteRef:
        key: coder-github-flow
        property: username
    - secretKey: client-secret
      remoteRef:
        key: coder-github-flow
        property: password
