---
operator:
  ingress:
    enabled: true
    ingressClassName: internal-nginx
    annotations:
      - external-dns.alpha.kubernetes.io/target: ingress-int.${SECRET_DOMAIN}
    host: tminio.${SECRET_DOMAIN}
