[tools]
talhelper = "latest"
k9s = "latest"
pre-commit = "latest"
yamlfmt = "latest"
task = "latest"
talosctl = "latest"
sops = "latest"
kustomize = "latest"
kubectl = "latest"
helm = "3.16.1"
age = "1.1.1"
flux2 = "latest"
krew = "latest"
helmfile = "1.0.0-rc.0"

[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/kubernetes/main/bootstrap/talos/clusterconfig/talosconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
