[tools]
talhelper = "latest"
k9s = "latest"
pre-commit = "latest"
yamlfmt = "latest"
task = "latest"
talosctl = "latest"
sops = "latest"
kustomize = "latest"
kubectl = "latest"
helm = "latest"
age = "latest"
flux2 = "latest"
krew = "latest"

[env]
KUBECONFIG = "{{config_root}}/kubeconfig"
TALOSCONFIG = "{{config_root}}/kubernetes/cluster-0/bootstrap/talos/clusterconfig/talosconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
