[tools]
talhelper = "3.0.19"
k9s = "latest"
pre-commit = "latest"
yamlfmt = "latest"
task = "latest"
talosctl = "1.9.4"
sops = "latest"
kustomize = "latest"
kubectl = "latest"
helm = "3.17.1"
age = "1.1.1"
flux2 = "latest"
krew = "latest"
helmfile = "0.171.0"

[env]
KUBECONFIG = "{{config_root}}/kubernetes/expanse/bootstrap/talos/clusterconfig/kubeconfig"
TALOSCONFIG = "{{config_root}}/kubernetes/expanse/bootstrap/talos/clusterconfig/talosconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
KUBERNETES_DIR = '{{config_root}}/kubernetes'
