[tools]
talhelper = "2.3.10"
k9s = "latest"
pre-commit = "latest"
yamlfmt = "latest"
task = "latest"
talosctl = "latest"
sops = "latest"
kustomize = "latest"
kubectl = "latest"
helm = "latest"
age = "1.1.0"
direnv = "latest"
flux2 = "latest"
