---
creation_rules:
  - path_regex: kubernetes/.*/talos/.*\.sops\.ya?ml$
    key_groups:
      - age:
          - age17hsqa2w74kzg0ylj8cm76jp8f7jdn855qcunzeuq4zs4vpws05jqrqpfsk
  - path_regex: kubernetes/.*\.sops\.ya?ml
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - age:
          - age17hsqa2w74kzg0ylj8cm76jp8f7jdn855qcunzeuq4zs4vpws05jqrqpfsk
  - path_regex: kubernetes/.*\.sops\.(env|ini|json|toml)
    key_groups:
      - age:
          - age17hsqa2w74kzg0ylj8cm76jp8f7jdn855qcunzeuq4zs4vpws05jqrqpfsk
  - path_regex: .*\.sops\.ya?ml
    key_groups:
      - age:
          - age17hsqa2w74kzg0ylj8cm76jp8f7jdn855qcunzeuq4zs4vpws05jqrqpfsk
