---
version: "3"
vars:
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes"
  CLUSTER_SECRETS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-secrets.sops.env"
  CLUSTER_SETTINGS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-settings.env"

env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

includes:
  flux:
    dir: .taskfiles/flux
    taskfile: .taskfiles/flux
  k8s:
    taskfile: .taskfiles/k8s
    dir: .taskfiles/k8s
  # externalsecrets:
  #   taskfile: .taskfiles/externalsecrets
  #   dir: .taskfiles/externalsecrets
  # rook:
  #   taskfile: ".taskfiles/rook"
  #   dir: .taskfiles/rook
  # volsync:
  #   taskfile: ".taskfiles/volsync"
  #   dir: .taskfiles/volsync

tasks:
  default:
    silent: true
    cmds:
      - task -l
