---
version: "3"
vars:
  CLUSTER: cluster-0
  CLUSTER_DIR: "{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}"
  CLUSTER_SECRETS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-secrets.sops.env"
  CLUSTER_SETTINGS_FILE: "{{.CLUSTER_DIR}}/flux/vars/cluster-settings.env"
  TALOS_DIR: "{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}/bootstrap/talos"
  TALOS_INTEGRATIONS_DIR: "{{.TALOS_DIR}}/"
  KUBERNETES_APP_DIR: "{{.ROOT_DIR}}/kubernetes/{{.CLUSTER}}/apps"


env:
  KUBECONFIG: "{{.ROOT_DIR}}/kubeconfig"
  SOPS_AGE_KEY_FILE: "{{.ROOT_DIR}}/age.key"

includes:
  flux:
    dir: .taskfiles/flux
    taskfile: .taskfiles/flux
  k8s:
    taskfile: .taskfiles/k8s
    dir: .taskfiles/k8s
  talos:
    taskfile: .taskfiles/talos
    dir: .taskfiles/talos
  externalsecrets:
    taskfile: .taskfiles/externalsecrets
    dir: .taskfiles/externalsecrets
  sops:
    taskfile: .taskfiles/sops
    dir: .taskfiles/sops


tasks:
  default:
    silent: true
    cmds:
      - task -l
