---
spegel:
  image:
    repository: ghcr.io/jfroy/spegel
    tag: "0.0.24-jfroy.3"
  spegel:
    containerdSock: /run/containerd/containerd.sock
    containerdRegistryConfigPath: /etc/cri/conf.d/hosts
  service:
    registry:
      hostPort: 29999
  serviceMonitor:
    enabled: true # TODO: Add later once I get the monitoring CRD setup
