---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.6.2
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: longhorn-values
