---
persistence:
  defaultClass: false
service:
  ui:
    type: ClusterIP
ingress:
  enabled: true
  ingressClassName: internal-nginx
  host: tlonghorn.${SECRET_DOMAIN}
  tls: true
defaultSettings:
  defaultDataPath: /var/mnt/sata
  backupTarget: "nfs://172.16.0.4:/volume1/k8s/longhorn-backups"
  replicaAutoBalance: "best-effort"
  defaultDataLocality: "best-effort"
annotations:
  configmap.reloader.stakater.com/reload: auto
enablePSP: false
