persistence:
  defaultClass: false # Don't set "longhorn" to be the default class
service:
  ui:
    type: ClusterIP
ingress:
  enabled: true
  ingressClassName: internal-nginx
  host: tlonghorn.${SECRET_DOMAIN}
  tls: true
  tlsSecret: bmrf.io-tls
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
defaultSettings:
  defaultDataPath: /var/mnt/sata
  backupTarget: "nfs://172.16.0.4:/volume1/k8s/longhorn-backups"
  replicaAutoBalance: "best-effort"
  defaultDataLocality: "best-effort"