---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: crunchy-postgres-operator
spec:
  interval: 30m
  chart:
    spec:
      chart: pgo
      version: 5.5.0
      sourceRef:
        kind: HelmRepository
        name: crunchydata
        namespace: flux-system
      interval: 5m
  maxHistory: 2
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    keepHistory: false
