---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: spegel-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
