---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-intel-device-plugins-operator
  namespace: flux-system
spec:
  path: "./kubernetes/cluster-0/apps/system/intel-device-plugins/operator"
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  interval: 10m
  prune: true
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-intel-device-plugins-gpu
  namespace: flux-system
spec:
  path: "./kubernetes/cluster-0/apps/system/intel-device-plugins/gpu"
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  interval: 30m
  prune: true
  wait: true
  dependsOn:
    - name: cluster-apps-intel-device-plugins-operator
