---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

tasks:
  sync:
    desc: Sync ExternalSecret resources
    summary: |
      Args:
        cluster: Cluster to run command against (required)
        ns: Namespace the PVC is in (default: default)
        secret: ExternalSecret to sync (required)
    silent: true
    vars:
      secret: "{{ .secret }}"
      ns: '{{.ns | default "default"}}'
      cluster: '{{ or .cluster (fail "Argument (cluster) is required") }}'
    cmd: kubectl --context {{.cluster}} -n {{.ns}} annotate externalsecret.external-secrets.io {{.secret}} force-sync=$(date +%s) --overwrite
    preconditions:
      - sh: kubectl --context {{.cluster}} -n {{.ns}} get es {{.secret}}
        msg: "ExternalSecret not found"

  sync-all:
    desc: Sync all ExternalSecrets for a cluster
    summary: |
      Args:
        cluster: Cluster to run command against (required)
    cmds:
      - for: { var: secrets, split: '' }
        task: sync
        vars:
          cluster: '{{.cluster}}'
          ns: '{{$a := split "|" .ITEM}}{{$a._0}}'
          secret: '{{$a := split "|" .ITEM}}{{$a._1}}'
    env:
      KUBECONFIG: "{{.KUBERNETES_DIR}}/{{.cluster}}/kubeconfig"
    requires:
      vars: ["cluster"]
    vars:
      secrets:
        sh: kubectl --context {{.cluster}} get externalsecret --all-namespaces --no-headers -A | awk '{print $1 "|" $2}'