---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: bmrf-ops
  namespace: flux-system
spec:
  interval: 30m
  url: https://github.com/kalenarndt/bmrf-ops.git
  ref:
    branch: main
  # secretRef:
  #   name: github-deploy-key
  ignore: |
    # exclude all
    /*
    # include kubernetes directory
    !/kubernetes
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster
  namespace: flux-system
spec:
  interval: 30m
  path: ./kubernetes/main/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  dependsOn:
    - name: flux
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cluster-settings
        optional: false
      - kind: Secret
        name: cluster-secrets
        optional: false
