---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-unifi-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-unifi-secrets
    creationPolicy: Owner
  data:
    - secretKey: unifi-username
      remoteRef:
        key: externaldns-unifi-secrets
        property: username
    - secretKey: unifi-password
      remoteRef:
        key: externaldns-unifi-secrets
        property: password
