---
fullnameOverride: &name externaldns-unifi
# logLevel: debug
provider:
  name: webhook
  webhook:
    image:
      repository: ghcr.io/kashalls/external-dns-unifi-webhook
      tag: v0.3.2@sha256:f8cf534970560bc8d1a61cc13f7c9580d91be60f5c6c7a86c3be0ca362208500
    env:
      - name: UNIFI_HOST
        value: https://${SECRET_UNIFI_HOST}
      - name: UNIFI_USER
        valueFrom:
          secretKeyRef:
            name: &secret externaldns-unifi-secrets
            key: unifi-username
      - name: UNIFI_PASS
        valueFrom:
          secretKeyRef:
            name: *secret
            key: unifi-password
      # - name: LOG_LEVEL
      #   value: "debug"
    livenessProbe:
      httpGet:
        path: /healthz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /readyz
        port: http-webhook
      initialDelaySeconds: 10
      timeoutSeconds: 5
extraArgs:
  - --ignore-ingress-tls-spec
policy: sync
sources: ["ingress", "service"]
txtOwnerId: main
txtPrefix: k8s.main.
domainFilters: ["${SECRET_DOMAIN}"]
serviceMonitor:
  enabled: true
podAnnotations:
  reloader.stakater.com/auto: "true"