---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-repositories
  namespace: flux-system
spec:
  interval: 10m
  path: ./kubernetes/cluster-0/flux/repositories
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  decryption:
    provider: sops
    secretRef:
      name: sops-age
