---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bmrf-7dtd-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: lh-two-retain-backup-standard
  resources:
    requests:
      storage: 20Gi