---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: talos
spec:
  # renovate: depName=ghcr.io/siderolabs/installer datasource=docker extractVersion=^(?<version>.*)$
  version: v1.6.5
  serviceAccountName: system-upgrade
  secrets:
    - name: talos
      path: /var/run/secrets/talos.dev
      ignoreUpdates: true
  concurrency: 1
  cordon: true
  drain:
    deleteLocalData: true
    disableEviction: false
    ignoreDaemonSets: true
  exclusive: true
  nodeSelector:
    matchExpressions:
      - key: kubernetes.io/os
        operator: In
        values:
          - linux
  tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    - key: node-role.kubernetes.io/master
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/controlplane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/control-plane
      operator: Exists
      effect: NoSchedule
    - key: node-role.kubernetes.io/etcd
      operator: Exists
      effect: NoSchedule
  prepare: &prepare
    image: ghcr.io/siderolabs/talosctl
    envs:
      - name: NODE_IP
        valueFrom:
          fieldRef:
            fieldPath: status.hostIP
    args:
      - --nodes=$(NODE_IP)
      - health
      - --server=false
  upgrade:
    <<: *prepare
    args:
      - --nodes=$(NODE_IP)
      - upgrade
      - --image=factory.talos.dev/installer/4ea1b20f73a7b3eac7faac4a02193470a85d0e2c441af474ddfd2de2e8da4dc7:$(SYSTEM_UPGRADE_PLAN_LATEST_VERSION)
      - --preserve=true
      - --wait=false
