---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-postgresql-user
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-postgresql-user
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: coder-postgresql-user
        property: password
    - secretKey: username
      remoteRef:
        key: coder-postgresql-user
        property: username
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-postgresql-su
  namespace: cert-manager
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: coder-postgresql-su
    creationPolicy: Owner
  data:
    - secretKey: password
      remoteRef:
        key: coder-postgresql-su
        property: password
    - secretKey: username
      remoteRef:
        key: coder-postgresql-su
        property: username

