---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: coder-postgresql-user
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    template:
      mergePolicy: Merge
      data:
        username: "{{ .username }}"
        password: "{{ .password }}"
        connection-url: "postgres://{{ .username }}:{{ .password }}@postgres-rw:5432/coder?sslmode=disable"
  data:
    - secretKey: password
      remoteRef:
        key: coder-postgresql-user
        property: password
    - secretKey: username
      remoteRef:
        key: coder-postgresql-user
        property: username
