---
version: "3"

x-task-vars: &task-vars
  cluster: "{{.cluster}}"
  node: "{{.node}}"
  ceph_disk: "{{.ceph_disk}}"
  ts: "{{.ts}}"
  jobName: "{{.jobName}}"

vars:
  waitForJobScript: "../_scripts/wait-for-k8s-job.sh"
  ts: '{{now | date "150405"}}'

tasks:
  password:
    desc: Gets the password for the rook dashboard
    silent: true
    cmds:
     - kubectl -n rook-ceph get secret rook-ceph-dashboard-password -o jsonpath="{['data']['password']}" | base64 --decode && echo

  wipe-talos03:
    desc: Trigger a wipe of Rook-Ceph data on node "talos01"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/disk/by-id/ata-INTEL_SSDSC2BX016T4R_BTHC626600GC1P6PGN"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: talos03

  wipe-node-enigma:
    desc: Trigger a wipe of Rook-Ceph data on node "enigma"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/disk/by-id/nvme-Samsung_SSD_980_1TB_S649NX0RB57050E"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: enigma

  wipe-node-felix:
    desc: Trigger a wipe of Rook-Ceph data on node "felix"
    cmds:
      - task: wipe-disk
        vars:
          node: "{{.node}}"
          ceph_disk: "/dev/disk/by-id/nvme-CT1000P1SSD8_202228759489"
      - task: wipe-data
        vars:
          node: "{{.node}}"
    vars:
      node: felix

  wipe-disk:
    desc: Wipe all remnants of rook-ceph from a given disk (ex. task rook:wipe-disk node=delta ceph_disk="/dev/nvme0n1")
    silent: true
    internal: true
    cmds:
      - envsubst < <(cat {{.wipeRookDiskJobTemplate}}) | kubectl --context {{.cluster}} apply -f -
      - bash {{.waitForJobScript}} {{.wipeCephDiskJobName}} default {{.cluster}}
      - kubectl --context {{.cluster}} -n default wait job/{{.wipeCephDiskJobName}} --for condition=complete --timeout=1m
      - kubectl --context {{.cluster}} -n default logs job/{{.wipeCephDiskJobName}} --container list
      - kubectl --context {{.cluster}} -n default delete job {{.wipeCephDiskJobName}}
    vars:
      cluster: '{{ or .cluster (fail "`cluster` is required") }}'
      node: '{{ or .node (fail "`node` is required") }}'
      ceph_disk: '{{ or .ceph_disk (fail "`ceph_disk` is required") }}'
      jobName: 'wipe-disk-{{- .node -}}-{{- .ceph_disk | replace "/" "-" -}}-{{- .ts -}}'
      wipeRookDiskJobTemplate: "WipeDiskJob.tmpl.yaml"
    env: *task-vars
    preconditions:
      - sh: test -f {{.waitForJobScript}}
      - sh: test -f {{.wipeRookDiskJobTemplate}}

  wipe-data:
    desc: Wipe all remnants of rook-ceph from a given disk (ex. task rook:wipe-data node=delta)
    silent: true
    internal: true
    cmds:
      - envsubst < <(cat {{.wipeRookDataJobTemplate}}) | kubectl --context {{.cluster}} apply -f -
      - bash {{.waitForJobScript}} {{.wipeRookDataJobName}} default {{.cluster}}
      - kubectl --context {{.cluster}} -n default wait job/{{.wipeRookDataJobName}} --for condition=complete --timeout=1m
      - kubectl --context {{.cluster}} -n default logs job/{{.wipeRookDataJobName}} --container list
      - kubectl --context {{.cluster}} -n default delete job {{.wipeRookDataJobName}}
    vars:
      cluster: '{{ or .cluster (fail "`cluster` is required") }}'
      node: '{{ or .node (fail "`node` is required") }}'
      jobName: "wipe-rook-data-{{- .node -}}-{{- .ts -}}"
      wipeRookDataJobTemplate: "WipeRookDataJob.tmpl.yaml"
    env: *task-vars
    preconditions:
      - sh: test -f {{.waitForJobScript}}
      - sh: test -f {{.wipeRookDataJobTemplate}}
