---
cluster:
  name: talos
  id: 1

cni:
  exclusive: false

bgp:
  enabled: false
  announce:
    loadbalancerIP: true
    podCIDR: false

bgpControlPlane:
  enabled: true

rollOutCiliumPods: true
localRedirectPolicy: true
envoy:
  enabled: false
k8sServiceHost: 127.0.0.1 # Kubeprism
k8sServicePort: 7445 # Kubeprism
kubeProxyReplacement: true
kubeProxyReplacementHealthzBindAddr: 0.0.0.0:10256

loadBalancer:
  algorithm: maglev
  mode: dsr

bandwidthManager:
  enabled: true
  bbr: true
bpf:
  masquerade: true
  tproxy: true

l7Proxy: true

ipam:
  mode: "kubernetes"

ingressController:
  enabled: false
  loadbalancerMode: shared

operator:
  rollOutPods: true

autoDirectNodeRoutes: true
ipv4NativeRoutingCIDR: 10.244.0.0/16
routingMode: native
enableRuntimeDeviceDetection: true

hubble:
  enabled: true
  serviceMonitor:
    enabled: true

  metrics:
    enabled:
      - dns:query
      - drop
      - tcp
      - flow
      - port-distribution
      - icmp
      - http

  relay:
    enabled: true
    rollOutPods: true

  ui:
    enabled: true
    ingress:
      enabled: true
      className: "internal-nginx"
      hosts:
        - hubble.bmrf.io
    rollOutPods: true

securityContext:
  capabilities:
    ciliumAgent:
      - CHOWN
      - KILL
      - NET_ADMIN
      - NET_RAW
      - IPC_LOCK
      - SYS_ADMIN
      - SYS_RESOURCE
      - DAC_OVERRIDE
      - FOWNER
      - SETGID
      - SETUID
    cleanCiliumState:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE

cgroup:
  autoMount:
    enabled: false
  hostRoot: /sys/fs/cgroup
