---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: authentik-redis
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.0.1
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-charts
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: authentik-redis-values
