---
controllers:
  terraria-calamity:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        # supplementalGroups:
        #   - 65542 # gladius:external-services
    containers:
      app:
        image:
          repository: ghcr.io/beardedio/terraria
          tag: tshock-5.2.0
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
            spec:
              failureThreshold: 30
              periodSeconds: 5
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false

service:
  app:
    controller: terraria-calamity
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "10.45.0.8"
    ports:
      http:
        port: 7777

persistence:
  files:
    existingClaim: terraria-calamity-pvc
    advancedMounts:
      terraria-calamity:
        app:
          - path: /config
            subPath: config
          - path: /tshock/ServerPlugins
            subPath: serverplugins