apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wnsZeyF2Wg==,iv:RZLdu/99yDwNvnLlpM7cNLf5beohBlqJNa48D8kUfqo=,tag:j6K1+jpVhq4PyxEShz7ONA==,type:str]
    SECRET_DOMAIN_EMAIL: ENC[AES256_GCM,data:dyXtbRml8isCs5yZ/F/qiAaq,iv:JlBm4o3FKnA38HIoqmOjVWgSgD07TzubsZDxhbyeV6w=,tag:Otyg6ZZEdqdaVYZmdhM/dg==,type:str]
    SECRET_EDNS_TSIG_KEY: ENC[AES256_GCM,data:qdRQZPucZD3R19AWXAsQG9UDeLeZpESvx0cvEK4OKJ4VGArwVEbwbk36z2M=,iv:sj7Z0K+725P5INTxgRXkDIzsQlOSm6k1Fb2Djim0x4g=,tag:yq4RuDVUN3PZyjOYcoq4rA==,type:str]
    SECRET_EDNS_TSIG_KEY_NAME: ENC[AES256_GCM,data:WJif4VK5fPS/DZgn,iv:Vs6/QLgcXDJZ9NQAeQKimeGM1oco1QQQDPcL0CH/Hg4=,tag:IV5qlAuIwxe14A1sPPMvhg==,type:str]
    SECRET_EDNS_HOST: ENC[AES256_GCM,data:lQP4abEqzrfRZQ==,iv:BzLTtJK66s2NfTdPruI9bAECbMp8N4UctY/8Qs0OZEY=,tag:akUPH6WCpChv05DkVfo9Zg==,type:str]
    SECRET_ONEPASSWORD_HOST: ENC[AES256_GCM,data:+cYSeKnTKr4N9A==,iv:YYkTFOrny+e3TjZtppVNBXL/l2tqv7MBP5QMASfQf2Y=,tag:77paPaUUp8rKvAJVYGnoBw==,type:str]
    SECRET_GEOIP_LICENSE_KEY: ENC[AES256_GCM,data:0O0GyzOod37fZStVB3KtVA==,iv:UukrVULuQYGiP7/oqFoaYHKdu95Bx3mdp1qrS3TMWp8=,tag:VkcGkYUPvlRWVM95hu9lEQ==,type:str]
    SECRET_GEOIP_ACCOUNT_ID: ENC[AES256_GCM,data:ANCmS+O9,iv:++FlWa0N8wxIXSX4SwVt4P/BvqmhvrMuagNhEKX7cgA=,tag:Q6xWscRKX4NfHEHrf3XAWg==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hsqa2w74kzg0ylj8cm76jp8f7jdn855qcunzeuq4zs4vpws05jqrqpfsk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPQjRQK295bGIvV1ZSVjha
            VHI4MEhxalYrN1MvQ05ZakQ2VEl2ZWxycXlZClZXNFVJZEIxdmZ4R3NFaUhUeE9k
            cWNjMkpkaVljRFNGV21jMzN1RkxSczgKLS0tIDluWHd6bmwzWWJYU1lraXUrUm1u
            ZlJtbi9VT3NIMGxPQ1VWeUgxdk05RG8KfVhjIAbVmt4iNWZYwoC7ORnzUhaEfQfn
            4wuUf+BOjGNN2Q13dPgQQO5jT47U7XynL1Mfec8GsnWJwWHIEvuhAw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-05-25T01:31:17Z"
    mac: ENC[AES256_GCM,data:USX21dig312mI7ulLjadUk628gyAqcUXLG11zMPwIzHAYTd8Jm8bCXXD7ArSbNBxWtJ6Re5iHtUBqOlnHl0yYUHjF3Jyw7Aw2yT7ETOmQs6IFXZBxcESNZep7jOoGekz+OOlpZR+7jQ0TcLROnYVwQN+9kaMpb2BLYHEEe1L9qY=,iv:rf9NQbSnIq4Nk2TJh5HqBbDDV77sSiCM5bWRYz0DOBc=,tag:+ANRBdEABUGXRef8H9/3OA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
