apiVersion: v1
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:9yn7mKC9cg==,iv:1k2oSbIzt1ro/uzGSpNL/7gBwJ4fXX6uElDwI5ty/pY=,tag:VT4w3Jb2lIBohD1Ozh6bzg==,type:str]
    SECRET_DOMAIN_EMAIL: ENC[AES256_GCM,data:TzI0+rE5gXIqu3BiAt58AVUH,iv:A8COc2SOa24I1mJImTMjlhAFyv70NG2qr2U4MIfJM+8=,tag:O4SDcRoXLjohdB5lQqrdYQ==,type:str]
    SECRET_EDNS_TSIG_KEY: ENC[AES256_GCM,data:QY4K2Od227O1zgHUl5ZSd6pDCQuQJFs68l+tl+KUHFh3cq2+FjcSgHzu6i8=,iv:zYxbb4c4QBrdDtky+jRX4IZmg2IISTz8tNiHRfVT8ro=,tag:Hf7lrV9itpTIKYNoZLYOkw==,type:str]
    SECRET_EDNS_TSIG_KEY_NAME: ENC[AES256_GCM,data:/ntsO7vQ5UG0Os0U,iv:5fzgfE7ffMvo0a3x4NK6B8t6wMgUAQ7DImUtVc417rU=,tag:LauVZvsF5+qzPhxQZVlShA==,type:str]
    SECRET_UNIFI_HOST: ENC[AES256_GCM,data:EUfXg5SF6eWh+g==,iv:SpZuQ6z0hH/6s4eaM3clgwDOrJYR5z4EUoTjH7a9KN4=,tag:Tft547/OrkNz0FEX5N5/LQ==,type:str]
    SECRET_EDNS_HOST: ENC[AES256_GCM,data:S8JuQIaEIqbeGQ==,iv:An31ilcAx9URuzurXzBE9R1xgkzcLWhOcgEXNX9YgPE=,tag:3DeqKA2SXsfZWFGes2xTEQ==,type:str]
    SECRET_ONEPASSWORD_HOST: ENC[AES256_GCM,data:cF9LpKFZstDdhw==,iv:wN8Y04B6l58jRw/lU9rQKwH0wGKX/IEd3NiaXZXH4tI=,tag:Sa6K3bUB5X0wttuO6iOLSg==,type:str]
    SECRET_GEOIP_LICENSE_KEY: ENC[AES256_GCM,data:w0aT6ZMiDQI1TytWwqSrAA==,iv:lkXcfHExHGnKvGyFGh4O1NA1Q0qdKdsm+9i5HiFuats=,tag:R2U1tStnR9pEei8sngMo6Q==,type:str]
    SECRET_GEOIP_ACCOUNT_ID: ENC[AES256_GCM,data:zcVh7rOG,iv:+mBGycHUjDOkiwRcXOTi0h81EZW0GHjkbk2JUKZdBHg=,tag:EKMY1k/xIm0WYb4iW+V6ew==,type:str]
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hsqa2w74kzg0ylj8cm76jp8f7jdn855qcunzeuq4zs4vpws05jqrqpfsk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRdy8ydHBCbXB1aW9aZkQ2
            MUQ2Sm90Z2YwNHcvbkNtR1ZNODhLNUU3a1Y4Cm5zeFZzazJGZ0hVNEFObndwNVFx
            UzBWQi9Ed0tGYy9Dd3NvelJ5c01pTFEKLS0tIEY1TEVmclZEekdPemI4M0lkeVdt
            TzVTWXZSOEJyZkxwc3NJa3VIWjgvY0UKDDi5o06/41CUg4M4Y7R81ik0Lunw8+ZA
            iVvDhRHSVFnJHwrFPILTeAa5A0pzx8lCKmKhEmBl27ohizZIZM18ag==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-09-06T15:21:04Z"
    mac: ENC[AES256_GCM,data:Z78esiIpZVKDtSkZQ6haqXc21AAX1MyIpB5MODQ0Cmp3hSApNqyqH9mwERSEnw+vbATG1LziqDV00Qc1uaV9LkIFcqinKerQ7tkREZgjHn3ne6fa7y3Mgj+GUgn4PyAX2vZ9CARu/O6fC3B2oumZfETYv2+z1q2VTwBZWtd87uA=,iv:9RccRcybiAxmAOF0SefiM2HdQ37DclV3/BzUbhbjKrc=,tag:NRQhIOoYNj9SO8wK1LHf+Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
