---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-weave-gitops
  namespace: flux-system
spec:
  interval: 10m
  path: "./kubernetes/cluster-0/apps/flux-system/weave-gitops/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: false
  dependsOn:
    - name: external-secrets-stores
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: capacitor
  namespace: flux-system
spec:
  targetNamespace: flux-system
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  wait: true
  prune: true
  path: "./"
  sourceRef:
    kind: OCIRepository
    name: capacitor