---
controllers:
  alertmanager:
    type: statefulset
    annotations:
      reloader.stakater.com/auto: "true"

    statefulset:
      volumeClaimTemplates:
        - name: storage
          accessMode: ReadWriteOnce
          size: 50Mi
          storageClass: ceph-block
          globalMounts:
            - path: /alertmanager

    containers:
      app:
        image:
          repository: quay.io/prometheus/alertmanager
          tag: v0.27.0
        ports:
          - name: http
            containerPort: 9093
        probes:
          liveness:
            enabled: true
          readiness:
            enabled: true
          startup:
            enabled: true
            spec:
              failureThreshold: 30
              periodSeconds: 5
        resources:
          requests:
            cpu: 11m
            memory: 50M
          limits:
            memory: 99M

service:
  app:
    controller: alertmanager
    ports:
      http:
        port: 9093

ingress:
  app:
    className: internal-nginx
    hosts:
      - host: &host alertmanager.${SECRET_DOMAIN}
        paths:
          - path: /
            service:
              identifier: app
              port: http
    tls:
      - hosts:
          - *host

persistence:
  config:
    type: configMap
    name: alertmanager-configmap
    globalMounts:
      - path: /etc/alertmanager
  secrets:
    type: secret
    name: alertmanager-secret
    globalMounts:
      - path: /etc/secrets