---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: system
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: reloader-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
