---
fullnameOverride: reloader
reloader:
  reloadStrategy: annotations
  podMonitor:
    enabled: true
  deployment:
    resources:
      requests:
        cpu: 5m
        memory: 144Mi
      limits:
        memory: 256Mi
