# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_SLACK_WEBHOOK_URL: ENC[AES256_GCM,data:Na5m/+Hu+ql2ytFPwVhngMnCUpw1GkjfWA29HyrGv+rvcSHMhJASfTUhb4cYsIXErQInZRkjSf3V5qlOKwx99nWvhwPqxgRY4U/0eSaNbO/S,iv:b4HMPIImVH8XrOcVL2xXrDRnewcDyLFottXKgD66BKs=,tag:d9e1aMsQb7nhyCZ1AdraZw==,type:str]
    SECRET_DOMAIN: ENC[AES256_GCM,data:u4YI5CDMww==,iv:jRtlhkbq9chI8uVPeTSEEsQzhDT+r7cOSSzEywVKIbA=,tag:nn08UQBgck3RS4yBYJdQCw==,type:str]
    SECRET_DOMAIN_EMAIL: ENC[AES256_GCM,data:JF0NVP6TP2yY97Qr9qjzul4Ynmo=,iv:/q7JglbbZI/SiRPoxgZVR/XozSDGUYoWNoOkq2KxWsw=,tag:fiU29Vxo80cYT4t5GbSfkA==,type:str]
    SECRET_SLACK_BOT_TOKEN: ENC[AES256_GCM,data:1qfDvKhZaYJaVApFCBR2jOLhwhAxg1CudhLRdacw2rLE8eBAbCTiGHRsbsUQHSvOusXDjD4jWagF,iv:nBR6Ul3yiZTX/d3tLcyODjXMWGmE2Bf4pp/+qPSfMdE=,tag:Q+M+TQ536luy9uwxeSSTEg==,type:str]
    SECRET_SLACK_APP_TOKEN: ENC[AES256_GCM,data:o2+nNvwO3rMgNP8Vdbtald0qrGfIaUyOTcHKrTmTJPRXPknCxbII1PtQ0c7nT0a4eezeGrtdLPmMXZxQSsKeyw61om2Lqxob2c/GYk0nqIHQYw2tQtgsaBiG5QvyzWsZQA==,iv:pbibWb/mfp9AfzxlUf2IV8YWJJsiabl+bstRnkdn0lk=,tag:cLGkBPAHzxb4RgWr9ulE2Q==,type:str]
    SECRET_SLACK_CHANNEL: ENC[AES256_GCM,data:FgTmEkGERvMGN9+edFk=,iv:8lLRGhrtB1JKCNAo4dC4L6GgSeDkdkDm8TuC7Kb5d/A=,tag:Tr8xtMSCoEc3z/xV/+u0Wg==,type:str]
    SECRET_EDNS_TSIG_KEY: ENC[AES256_GCM,data:02+9L7h41dY5d/AJybCGKJdEXZP3K3i/WHiTsRAfLgnH+OpFjxBZFNVeHME=,iv:Z7W1XYinhvDcUwfM9tJw6Gcc58GIRW1UqBs8fxS6YGI=,tag:jP1WJsGkg7wBqzB1JwVoHA==,type:str]
    SECRET_EDNS_TSIG_KEY_NAME: ENC[AES256_GCM,data:gXh4zTYh203CjpP0,iv:7yu+N85wsjgBV8wu1ExJG8E0UZDqqBslyCxKpPtgO4M=,tag:WF6y4icHJ2ITckQ+vYSYPg==,type:str]
    SECRET_EDNS_HOST: ENC[AES256_GCM,data:/mdPoAgI+ZL6/A==,iv:I/jZfOfemvLb6HqSFlzckbK4FmkoR5QrrU7RNF/s14Y=,tag:4t6fJ9/ChCm5+x6R2GVacA==,type:str]
    SECRET_WEAVE_HASH: ENC[AES256_GCM,data:Np7uD/QP8q2/bV/boTPedsOYIEkI2RB0PcQe8SZ8q3UN3sktQW7I2+piFkxdN1S6HBztNK6ZkPuU6UYL,iv:TJ1uq41+UpxvqMzniqBgZpjpljGE/L6HG1BnfvJ4vX0=,tag:0RGxii2F9MkFkHNga2oV1A==,type:str]
    SECRET_AUTHETIK_HASH: ENC[AES256_GCM,data:Ckv9YTy5UP1qYEjvzpZ9+0MJBZruqoDtKQZLwn/BKArUkNFaLUCqPg5kR4j1goaHcBo=,iv:YO8uthcXM5WIzZMlVua9W68SDCAWVRHMufOIBuFHgk4=,tag:fFQJh57ZJlOYPP0xqBvQKw==,type:str]
    SECRET_GEOIP_LICENSE_KEY: ENC[AES256_GCM,data:v5pRAB7cP0cKsXl8JyKi7g==,iv:csF98+Kie+ukbgr6T2SMLHKBFMa8KzBZwyKSKfgEUIw=,tag:RZ+ZHNrItnY8xn1xDN/Ziw==,type:str]
    SECRET_GEOIP_ACCOUNT_ID: ENC[AES256_GCM,data:1vzBpyYQ,iv:IXrrava6jjyALn7IBGyKsPNsy/a/fBMgYjMTtv+eTMU=,tag:MnrtfSQdTaj8T3TUwpWedg==,type:str]
    SECRET_AUTHENTIK_PG_PASSWORD: ENC[AES256_GCM,data:yGBsfNJVQnh+Yg==,iv:KV1K0AzUkwa8UswPhod5R7GPF7McI/mQa1xy0t/9sp0=,tag:tYhmk1GpMEkvtAm/3oUsQg==,type:str]
    SECRET_TFE_ENCRYPTION_PASSWORD: ENC[AES256_GCM,data:SAMh6s17wSoypBFZLvBx,iv:+rq/fh8ecROt0+b7lZ/8JpiMPtDVFCdxfHzJJiIse+I=,tag:7UHfxixroZ5UA5JrjNlVVw==,type:str]
    SECRET_TFE_PGSQL_USERNAME: ENC[AES256_GCM,data:2HZ2w6j1Mw==,iv:/9G50OB6pwLFcfVTpr0wgVk3uFOMZF6JnJVtHh/6oL8=,tag:v3omb4QlbzTUZF8cVlrSEA==,type:str]
    SECRET_TFE_PGSQL_PASSWORD: ENC[AES256_GCM,data:6BfxFg17w1KmYSqXq3DtkW5Bg2I=,iv:+Jjw48Fh29awpbWrF8UzRQ11F53S6eGZjNca7kSYSrI=,tag:buBZOkBk3NGDfZxPHzvZJA==,type:str]
    SECRET_TFE_PGSQL_DB_NAME: ENC[AES256_GCM,data:zhZ6tuCT0Q==,iv:M0vkMdH400Ydi7TAmeuEVXNZIWXlWn1JRb6eq87MzFQ=,tag:WoZ9ikVH5BxequMvVpemkg==,type:str]
    SECRET_ONEPASSWORD_HOST: ENC[AES256_GCM,data:xXDDPrh8PtgOoQ==,iv:8B1tmR7FvgEQAqhLOTmxhEnlEahEW/iq7VFgEaL410c=,tag:YZ/RRLmD2SouTaRyfxSsXA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age17hsqa2w74kzg0ylj8cm76jp8f7jdn855qcunzeuq4zs4vpws05jqrqpfsk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvWUFyRkRHRWZVSGdzbzdz
            cFhjbWhBTVljWGl4L0pjekV1bEYzbXJlYmlBCjUrem1vN211NDNrSWgxQkdSMVRw
            WWtjSTI4RUdKMVhtZENWSktLVTdobWMKLS0tIEo1VG1TVk5sWTc1Q040OFV5bENQ
            RFBxdHdtM3ZQKzhzZWRKQldWbU5Yd1UKkU4VM+34ih/IAtbC63g6RzCTUnPOZNWE
            +WP7HuhcR6caLAPq55vUfJoMFNQ0RDg/TqnhaO3ijQjDIjesyCt5gQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-10-29T20:41:47Z"
    mac: ENC[AES256_GCM,data:rAfA3Ws/wIDLWOJRs93vwkeaWfwcKO36iktmhUrVl+EyrLx9oeSzuQEDpAd+6B2Xj9Msiy44+bL5kdrtIv2JzHcfSDXkBTEWocJstFn1Rm7EKfzqDLO90VaxlZp1f059KwE4aZAg/5X8gu0y0n0VZZeNZD5g/1v9l6gzwQTKS3Y=,iv:DpVoxM4K/mV0zkFKMMf2ZJs9K5CZUIX7HiP4UzsGc1U=,tag:xS7I0iBTn6twOHsgvXtIaA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
