---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: coder
  namespace: media
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 0.27.3
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: coder-values