coder:
  podAnnotations:
    reloader.stakater.com/auto: "true"

  env:
    - name: CODER_ACCESS_URL
      value: "https://coder.${SECRET_DOMAIN}"
    - name: CODER_PG_CONNECTION_URL
      value: "postgres://postgres:cGFzc3dvcmQ=@postgres-rw.cloudnative-pg.svc.cluster.local:5432/coder?sslmode=disable"
  ingress:
    enable: true
    className: "internal-nginx"
    host: coder.${SECRET_DOMAIN}
    # coder.ingress.wildcardHost -- The wildcard hostname to match on. Should be
    # in the form "*.example.com" or "*-suffix.example.com". If you are using a
    # suffix after the wildcard, the suffix will be stripped from the created
    # ingress to ensure that it is a legal ingress host. Optional if not using
    # applications over subdomains.
    # Be sure to also set CODER_WILDCARD_ACCESS_URL within coder.env[]
    wildcardHost: ""
  service:
    enable: true
    type: ClusterIP
    tls:
      enable: true
      secretName: ${SECRET_DOMAIN}-tls