---
replicas: 3
kind: Deployment
deschedulerPolicyAPIVersion: descheduler/v1alpha2
deschedulerPolicy:
  profiles:
    - name: Default
      pluginConfig:
        - name: DefaultEvictor
          args:
            evictFailedBarePods: true
            evictLocalStoragePods: true
            evictSystemCriticalPods: true
            nodeFit: true
        - name: RemovePodsViolatingInterPodAntiAffinity
        - name: RemovePodsViolatingNodeAffinity
        - name: RemovePodsViolatingNodeTaints
        - name: RemovePodsViolatingTopologySpreadConstraint
          args:
            constraints:
              - DoNotSchedule
              - ScheduleAnyway
      plugins:
        balance:
          enabled:
            - RemovePodsViolatingTopologySpreadConstraint
        deschedule:
          enabled:
            - RemovePodsViolatingInterPodAntiAffinity
            - RemovePodsViolatingNodeAffinity
            - RemovePodsViolatingNodeTaints
service:
  enabled: true
serviceMonitor:
  enabled: true
leaderElection:
  enabled: true