---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname_shared nginx-shared
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname_shared
  interval: 10m
  path: "./kubernetes/main/apps/network/nginx/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: true
  dependsOn:
    - name: cert-manager-issuers
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname_external nginx-external
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname_external
  interval: 10m
  path: "./kubernetes/main/apps/network/nginx/external"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: false
  dependsOn:
    - name: nginx-shared
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname_internal nginx-internal
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname_internal
  interval: 10m
  path: "./kubernetes/main/apps/network/nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: false
  dependsOn:
    - name: nginx-shared
