---
controllers:
  bmrf-7dtd:
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      securityContext:
        runAsUser: 0
        runAsGroup: 0
        runAsNonRoot: false
        fsGroup: 0
        fsGroupChangePolicy: OnRootMismatch
        # supplementalGroups:
        #   - 65542 # gladius:external-services
    containers:
      app:
        image:
          repository: vinanrra/7dtd-server
          tag: latest
        probes:
          liveness:
            enabled: false
          readiness:
            enabled: false
          startup:
            enabled: false
            spec:
              failureThreshold: 30
              periodSeconds: 5
        env:
          VERSION: stable
          CHANGE_CONFIG_DIR_OWNERSHIP: true
          TZ: ${TZ}
          START_MODE: 1
          MONITOR: YES
          BACKUP: YES
        securityContext:
          allowPrivilegeEscalation: true
          readOnlyRootFilesystem: false

service:
  app:
    controller: bmrf-7dtd
    type: LoadBalancer
    annotations:
      io.cilium/lb-ipam-ips: "10.45.0.8"
    ports:
      http:
        port: 26900
        protocol: TCP
      http2:
        port: 26900
        protocol: UDP
      server1:
        port: 26901
        protocol: UDP
      server2:
        port: 26902
        protocol: UDP
      server3:
        port: 8080
        protocol: TCP

persistence:
  files:
    existingClaim: bmrf-7dtd2-pvc
    advancedMounts:
      bmrf-7dtd:
        app:
          - path: /home/sdtdserver/.local/share/7DaysToDie/
            subPath: config
          - path: /home/sdtdserver/serverfiles/
            subPath: serverfiles