---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-internal-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-internal-secrets
    creationPolicy: Owner
  data:
    - secretKey: rndc-secret
      remoteRef:
        key: externaldns-internal-secrets
        property: rndc-secret
    - secretKey: rndc-alg
      remoteRef:
        key: externaldns-internal-secrets
        property: rndc-alg
    - secretKey: rndc-keyname
      remoteRef:
        key: externaldns-internal-secrets
        property: rndc-keyname
