---
podAnnotations:
  secret.reloader.stakater.com/reload: externaldns-internal-secrets
  configmap.reloader.stakater.com/reload: auto

interval: 1m
logLevel: debug
provider: rfc2136
env:
  - name: EXTERNAL_DNS_RFC2136_HOST
    value: "172.16.2.2"
  - name: EXTERNAL_DNS_RFC2136_PORT
    value: "5354"
  - name: EXTERNAL_DNS_RFC2136_ZONE
    value: "${SECRET_DOMAIN}"
  - name: EXTERNAL_DNS_RFC2136_TSIG_AXFR
    value: "true"
  - name: EXTERNAL_DNS_RFC2136_TSIG_KEYNAME
    valueFrom:
      secretKeyRef:
        name: externaldns-internal-secrets
        key: rndc-keyname
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET_ALG
    valueFrom:
      secretKeyRef:
        name: externaldns-internal-secrets
        key: rndc-alg
  - name: EXTERNAL_DNS_RFC2136_TSIG_SECRET
    valueFrom:
      secretKeyRef:
        name: externaldns-internal-secrets
        key: rndc-secret
policy: sync
sources:
  - ingress
  - service
txtPrefix: "_owner."
txtOwnerId: talos

resources:
  requests:
    cpu: 16m
    memory: 90M
  limits:
    memory: 90M