---
defaultPodOptions:
  securityContext:
    runAsNonRoot: true
    runAsUser: 65534
    runAsGroup: 65534
    seccompProfile:
      type: RuntimeDefault


controllers:
  app:
    strategy: RollingUpdate
    annotations:
      reloader.stakater.com/auto: "true"

    pod:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node-role.kubernetes.io/control-plane
                    operator: Exists
      tolerations:
        - key: CriticalAddonsOnly
          operator: Exists
        - key: node-role.kubernetes.io/master
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/controlplane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
        - key: node-role.kubernetes.io/etcd
          operator: Exists
          effect: NoExecute

    containers:
      app:
        image:
          repository: ghcr.io/buroa/system-upgrade-controller
          tag: v0.14.3@sha256:8f2916ef30fd50648ecb0fa3fba3bf8fff9e0e3529f1bf736c0026f347e87d5a
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        env:
          SYSTEM_UPGRADE_CONTROLLER_DEBUG: false
          SYSTEM_UPGRADE_CONTROLLER_THREADS: 2
          SYSTEM_UPGRADE_JOB_ACTIVE_DEADLINE_SECONDS: 900
          SYSTEM_UPGRADE_JOB_BACKOFF_LIMIT: 99
          SYSTEM_UPGRADE_JOB_IMAGE_PULL_POLICY: IfNotPresent
          SYSTEM_UPGRADE_JOB_KUBECTL_IMAGE: docker.io/rancher/kubectl:v1.29.2
          SYSTEM_UPGRADE_JOB_PRIVILEGED: true
          SYSTEM_UPGRADE_JOB_TTL_SECONDS_AFTER_FINISH: 900
          SYSTEM_UPGRADE_PLAN_POLLING_INTERVAL: 15m
          SYSTEM_UPGRADE_CONTROLLER_NAME: system-upgrade-controller
          SYSTEM_UPGRADE_CONTROLLER_NAMESPACE:
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace

persistence:
  etc-ssl:
    type: hostPath
    hostPath: /etc/ssl
    hostPathType: DirectoryOrCreate
    globalMounts:
      - path: /etc/ssl
        readOnly: true
  etc-pki:
    type: hostPath
    hostPath: /etc/pki
    hostPathType: DirectoryOrCreate
    globalMounts:
      - path: /etc/pki
        readOnly: true
  etc-ca-certificates:
    type: hostPath
    hostPath: /etc/ca-certificates
    hostPathType: DirectoryOrCreate
    globalMounts:
      - path: /etc/ca-certificates
        readOnly: true
  tmp:
    type: emptyDir

serviceAccount:
  name: system-upgrade
  create: true
