---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: coder
spec:
  interval: 30m
  chart:
    spec:
      chart: coder
      version: 2.14.0
      sourceRef:
        kind: HelmRepository
        name: coder
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: coder-values
