---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-longhorn
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/cluster-0/apps/storage/longhorn/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: true
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-storage-longhorn-jobs
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/cluster-0/apps/storage/longhorn/app/jobs"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: true
  dependsOn:
    - name: cluster-apps-storage-longhorn
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cluster-apps-longhorn-storage-longhorn-classes
  namespace: flux-system
spec:
  interval: 30m
  path: "./kubernetes/cluster-0/apps/storage/longhorn/app/storage-classes"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: true
  dependsOn:
    - name: cluster-apps-storage-longhorn
