---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: weave-gitops-secrets
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: weave-gitops-secrets
    creationPolicy: Owner
  data:
    - secretKey: admin-password
      remoteRef:
        key: weave-gitops
        property: admin-password
