---
podAnnotations:
  secret.reloader.stakater.com/reload: weave-gitops-secrets

logLevel: info

adminUser:
  create: true
  username: admin

networkPolicy:
  create: false

metrics:
  enabled: false

rbac:
  create: true
  impersonationResourceNames:
    - *admin_user
  additionalRules:
    - apiGroups:
        - "infra.contrib.fluxcd.io"
      resources:
        - "terraforms"
      verbs:
        - "get"
        - "list"
        - "patch"

ingress:
  enabled: true
  className: internal-nginx
  hosts:
    - host: tgitops.bmrf.io
      paths:
        - path: /
          pathType: Prefix
  # tls:
  #   - hosts:
  #       - *host


