---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &secret authentik-redis-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *secret
    creationPolicy: Owner
  data:
    - secretKey: authentik-redis-password
      remoteRef:
        key: *secret
        property: authentik-redis-password
