---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # Pre Flux-Kustomizations
  - ./namespace.yaml
  # Flux-Kustomizations
  # - ./add-ons/ks.yaml #TODO: Add this later 
  - ./weave-gitops/ks.yaml
