---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname system-upgrade-controller
  namespace: flux-system
spec:
  targetNamespace: system-controllers
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/main/apps/system-controllers/system-upgrade-controller/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: true
  timeout: 2m
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname system-upgrade-controller-plans
  namespace: flux-system
spec:
  targetNamespace: system-controllers
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  interval: 10m
  path: "./kubernetes/main/apps/system-controllers/system-upgrade-controller/plans"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: false
  timeout: 2m
  dependsOn:
    - name: system-upgrade-controller
  postBuild:
    substitute:
      TALOS_SCHEMATIC_ID: d7b0152eb7c48cb37db36b5ec299224b7a07e5ed9a55a3eb63c4105364f180d6
      # renovate: depName=ghcr.io/siderolabs/installer datasource=docker extractVersion=^(?<version>.*)$
      TALOS_VERSION: v1.8.3
      # renovate: depName=ghcr.io/siderolabs/kubelet datasource=docker extractVersion=^(?<version>.*)$
      KUBERNETES_VERSION: v1.32.3
