---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: spegel
spec:
  interval: 30m
  chart:
    spec:
      chart: spegel
      version: v0.0.18
      sourceRef:
        kind: HelmRepository
        name: xenitab
        namespace: flux-system
      interval: 30m
  maxHistory: 2
  install:
    remediation:
      retries: 5
    crds: CreateReplace
  upgrade:
    remediation:
      retries: 5
    crds: CreateReplace
    cleanupOnFail: true
  uninstall:
    keepHistory: false
  valuesFrom:
    - kind: ConfigMap
      name: spegel-values
