---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname_calamity calamity-terraria
  namespace: flux-system
spec:
  targetNamespace: games
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname_calamity
  interval: 10m
  path: ./kubernetes/main/apps/games/terraria/calamity/app/
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: false
  dependsOn:
    - name: longhorn-storage
