---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname_shared cluster-apps-nginx-shared
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname_shared
  interval: 10m
  path: "./kubernetes/cluster-0/apps/network/nginx/shared"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: true
  dependsOn:
    - name: cluster-apps-cert-manager-issuers
# ---
# # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
# apiVersion: kustomize.toolkit.fluxcd.io/v1
# kind: Kustomization
# metadata:
#   name: &appname_external cluster-apps-nginx-external
#   namespace: flux-system
# spec:
#   targetNamespace: network
#   commonMetadata:
#     labels:
#       app.kubernetes.io/name: *appname_external
#   interval: 10m
#   path: "./kubernetes/cluster-0/apps/network/nginx/external"
#   prune: true
#   sourceRef:
#     kind: GitRepository
#     name: bmrf-ops
#   wait: false
#   dependsOn:
#     - name: cluster-apps-nginx-shared
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname_internal cluster-apps-nginx-internal
  namespace: flux-system
spec:
  targetNamespace: network
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname_internal
  interval: 10m
  path: "./kubernetes/cluster-0/apps/network/nginx/internal"
  prune: true
  sourceRef:
    kind: GitRepository
    name: bmrf-ops
  wait: false
  dependsOn:
    - name: cluster-apps-nginx-shared
