---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: externaldns-external-secrets
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: externaldns-external-secrets
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-api-token
      remoteRef:
        key: Cloudflare
        property: api-token
