---
csiDriver:
  name: "org.democratic-csi.local-hostpath"
  attachRequired: false
  storageCapacity: true # With storage capacity tracking, the scheduler filters out nodes which do not have enough capacity.
  fsGroupPolicy: File # fsGroupChangePolicy

storageClasses:
  - name: local-hostpath
    defaultClass: false
    reclaimPolicy: Delete
    volumeBindingMode: Immediate
    # distributed support is not yet ready for expansion
    allowVolumeExpansion: false

controller:
  enabled: true
  strategy: node
  externalAttacher:
    enabled: false
  externalProvisioner:
    enabled: true
    extraArgs:
      - --leader-election=false
      - --node-deployment=true
      - --node-deployment-immediate-binding=true
      - --feature-gates=Topology=true
      - --strict-topology=true
      - --enable-capacity=true
      - --capacity-ownerref-level=1
  externalResizer:
    enabled: false
  externalSnapshotter:
    enabled: false
    extraArgs:
      - --leader-election=false
      - --node-deployment=true

node:
  driver:
    extraVolumeMounts:
      - name: local-hostpath
        mountPath: /var/mnt/sata/demo-csi-local-path
        mountPropagation: Bidirectional

  extraVolumes:
    - name: local-hostpath
      hostPath:
        path: /var/mnt/sata/csi-local-path
        type: DirectoryOrCreate

driver:
  config:
    driver: local-hostpath
    instance_id:
    local-hostpath:
      shareBasePath: "/var/mnt/sata/csi-local-path"
      controllerBasePath: "/var/mnt/sata/csi-local-path"
      dirPermissionsMode: "0770"
      dirPermissionsUser: 0
      dirPermissionsGroup: 0