---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./helmrelease.yaml
configMapGenerator:
  - name: actions-runners-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml