runnerScaleSetName: arc-runner-set-bmrf-ops

githubConfigUrl: https://github.com/kalenarndt/bmrf-ops

minRunners: 0
maxRunners: 6

containerMode:
  type: "dind"

controllerServiceAccount:
  name: actions-runner-controller-gha-rs-controller
  namespace: system-controllers

listenerTemplate:
  metadata:
    labels:
      app.kubernetes.io/name: arc-bmrf-ops-listener
  spec:
    containers: []

template:
  metadata:
    labels:
      app.kubernetes.io/name: arc-bmrf-ops-runner
  spec:
    containers:
      - name: runner
        image: ghcr.io/onedr0p/actions-runner:2.319.1
        command: ["/home/runner/run.sh"]